/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import GameManager;
	import laya.ui.Widget;
	import laya.display.Text;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 1280;
		public static var height:int = 720;
		public static var scaleMode:String = "full";
		public static var screenMode:String = "none";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "Main.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = false;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("GameManager",GameManager);
			reg("laya.ui.Widget",Widget);
			reg("laya.display.Text",Text);
		}
		GameConfig.init();
	}
}